name: Terraform CI

on:
  push:
    branches:
      - main
      - staging
      - dev

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      TF_WORKSPACE: ${{github.ref_name}}  # branch name maps to workspace

    steps:
      # checkout repo
      - name: Checkout
        uses: actions/checkout@v3

      # steup terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.15.1

       # configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_ID }}
           aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init
        

      - name: Terraform Validate
        run: terraform validate
        

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan
       
